# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dominik/Desktop/TOWER_2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dominik/Desktop/TOWER_2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dominik/Desktop/TOWER_2/CMakeFiles /home/dominik/Desktop/TOWER_2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dominik/Desktop/TOWER_2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named out

# Build rule for target.
out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 out
.PHONY : out

# fast build rule for target.
out/fast:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/build
.PHONY : out/fast

src/Animation/Clip.o: src/Animation/Clip.cpp.o

.PHONY : src/Animation/Clip.o

# target to build an object file
src/Animation/Clip.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/Clip.cpp.o
.PHONY : src/Animation/Clip.cpp.o

src/Animation/Clip.i: src/Animation/Clip.cpp.i

.PHONY : src/Animation/Clip.i

# target to preprocess a source file
src/Animation/Clip.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/Clip.cpp.i
.PHONY : src/Animation/Clip.cpp.i

src/Animation/Clip.s: src/Animation/Clip.cpp.s

.PHONY : src/Animation/Clip.s

# target to generate assembly for a file
src/Animation/Clip.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/Clip.cpp.s
.PHONY : src/Animation/Clip.cpp.s

src/Animation/Pose.o: src/Animation/Pose.cpp.o

.PHONY : src/Animation/Pose.o

# target to build an object file
src/Animation/Pose.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/Pose.cpp.o
.PHONY : src/Animation/Pose.cpp.o

src/Animation/Pose.i: src/Animation/Pose.cpp.i

.PHONY : src/Animation/Pose.i

# target to preprocess a source file
src/Animation/Pose.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/Pose.cpp.i
.PHONY : src/Animation/Pose.cpp.i

src/Animation/Pose.s: src/Animation/Pose.cpp.s

.PHONY : src/Animation/Pose.s

# target to generate assembly for a file
src/Animation/Pose.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/Pose.cpp.s
.PHONY : src/Animation/Pose.cpp.s

src/Animation/Skeleton.o: src/Animation/Skeleton.cpp.o

.PHONY : src/Animation/Skeleton.o

# target to build an object file
src/Animation/Skeleton.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/Skeleton.cpp.o
.PHONY : src/Animation/Skeleton.cpp.o

src/Animation/Skeleton.i: src/Animation/Skeleton.cpp.i

.PHONY : src/Animation/Skeleton.i

# target to preprocess a source file
src/Animation/Skeleton.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/Skeleton.cpp.i
.PHONY : src/Animation/Skeleton.cpp.i

src/Animation/Skeleton.s: src/Animation/Skeleton.cpp.s

.PHONY : src/Animation/Skeleton.s

# target to generate assembly for a file
src/Animation/Skeleton.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/Skeleton.cpp.s
.PHONY : src/Animation/Skeleton.cpp.s

src/Animation/SkinningData.o: src/Animation/SkinningData.cpp.o

.PHONY : src/Animation/SkinningData.o

# target to build an object file
src/Animation/SkinningData.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/SkinningData.cpp.o
.PHONY : src/Animation/SkinningData.cpp.o

src/Animation/SkinningData.i: src/Animation/SkinningData.cpp.i

.PHONY : src/Animation/SkinningData.i

# target to preprocess a source file
src/Animation/SkinningData.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/SkinningData.cpp.i
.PHONY : src/Animation/SkinningData.cpp.i

src/Animation/SkinningData.s: src/Animation/SkinningData.cpp.s

.PHONY : src/Animation/SkinningData.s

# target to generate assembly for a file
src/Animation/SkinningData.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Animation/SkinningData.cpp.s
.PHONY : src/Animation/SkinningData.cpp.s

src/Application.o: src/Application.cpp.o

.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i

.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s

.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/Core/Config.o: src/Core/Config.cpp.o

.PHONY : src/Core/Config.o

# target to build an object file
src/Core/Config.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Config.cpp.o
.PHONY : src/Core/Config.cpp.o

src/Core/Config.i: src/Core/Config.cpp.i

.PHONY : src/Core/Config.i

# target to preprocess a source file
src/Core/Config.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Config.cpp.i
.PHONY : src/Core/Config.cpp.i

src/Core/Config.s: src/Core/Config.cpp.s

.PHONY : src/Core/Config.s

# target to generate assembly for a file
src/Core/Config.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Config.cpp.s
.PHONY : src/Core/Config.cpp.s

src/Core/Convert.o: src/Core/Convert.cpp.o

.PHONY : src/Core/Convert.o

# target to build an object file
src/Core/Convert.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Convert.cpp.o
.PHONY : src/Core/Convert.cpp.o

src/Core/Convert.i: src/Core/Convert.cpp.i

.PHONY : src/Core/Convert.i

# target to preprocess a source file
src/Core/Convert.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Convert.cpp.i
.PHONY : src/Core/Convert.cpp.i

src/Core/Convert.s: src/Core/Convert.cpp.s

.PHONY : src/Core/Convert.s

# target to generate assembly for a file
src/Core/Convert.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Convert.cpp.s
.PHONY : src/Core/Convert.cpp.s

src/Core/Math3D.o: src/Core/Math3D.cpp.o

.PHONY : src/Core/Math3D.o

# target to build an object file
src/Core/Math3D.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Math3D.cpp.o
.PHONY : src/Core/Math3D.cpp.o

src/Core/Math3D.i: src/Core/Math3D.cpp.i

.PHONY : src/Core/Math3D.i

# target to preprocess a source file
src/Core/Math3D.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Math3D.cpp.i
.PHONY : src/Core/Math3D.cpp.i

src/Core/Math3D.s: src/Core/Math3D.cpp.s

.PHONY : src/Core/Math3D.s

# target to generate assembly for a file
src/Core/Math3D.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Math3D.cpp.s
.PHONY : src/Core/Math3D.cpp.s

src/Core/Random.o: src/Core/Random.cpp.o

.PHONY : src/Core/Random.o

# target to build an object file
src/Core/Random.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Random.cpp.o
.PHONY : src/Core/Random.cpp.o

src/Core/Random.i: src/Core/Random.cpp.i

.PHONY : src/Core/Random.i

# target to preprocess a source file
src/Core/Random.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Random.cpp.i
.PHONY : src/Core/Random.cpp.i

src/Core/Random.s: src/Core/Random.cpp.s

.PHONY : src/Core/Random.s

# target to generate assembly for a file
src/Core/Random.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Random.cpp.s
.PHONY : src/Core/Random.cpp.s

src/Core/Timer.o: src/Core/Timer.cpp.o

.PHONY : src/Core/Timer.o

# target to build an object file
src/Core/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Timer.cpp.o
.PHONY : src/Core/Timer.cpp.o

src/Core/Timer.i: src/Core/Timer.cpp.i

.PHONY : src/Core/Timer.i

# target to preprocess a source file
src/Core/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Timer.cpp.i
.PHONY : src/Core/Timer.cpp.i

src/Core/Timer.s: src/Core/Timer.cpp.s

.PHONY : src/Core/Timer.s

# target to generate assembly for a file
src/Core/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Core/Timer.cpp.s
.PHONY : src/Core/Timer.cpp.s

src/Debug/DebugMenu.o: src/Debug/DebugMenu.cpp.o

.PHONY : src/Debug/DebugMenu.o

# target to build an object file
src/Debug/DebugMenu.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Debug/DebugMenu.cpp.o
.PHONY : src/Debug/DebugMenu.cpp.o

src/Debug/DebugMenu.i: src/Debug/DebugMenu.cpp.i

.PHONY : src/Debug/DebugMenu.i

# target to preprocess a source file
src/Debug/DebugMenu.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Debug/DebugMenu.cpp.i
.PHONY : src/Debug/DebugMenu.cpp.i

src/Debug/DebugMenu.s: src/Debug/DebugMenu.cpp.s

.PHONY : src/Debug/DebugMenu.s

# target to generate assembly for a file
src/Debug/DebugMenu.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Debug/DebugMenu.cpp.s
.PHONY : src/Debug/DebugMenu.cpp.s

src/Debug/Log.o: src/Debug/Log.cpp.o

.PHONY : src/Debug/Log.o

# target to build an object file
src/Debug/Log.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Debug/Log.cpp.o
.PHONY : src/Debug/Log.cpp.o

src/Debug/Log.i: src/Debug/Log.cpp.i

.PHONY : src/Debug/Log.i

# target to preprocess a source file
src/Debug/Log.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Debug/Log.cpp.i
.PHONY : src/Debug/Log.cpp.i

src/Debug/Log.s: src/Debug/Log.cpp.s

.PHONY : src/Debug/Log.s

# target to generate assembly for a file
src/Debug/Log.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Debug/Log.cpp.s
.PHONY : src/Debug/Log.cpp.s

src/Gameplay/Camera.o: src/Gameplay/Camera.cpp.o

.PHONY : src/Gameplay/Camera.o

# target to build an object file
src/Gameplay/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Gameplay/Camera.cpp.o
.PHONY : src/Gameplay/Camera.cpp.o

src/Gameplay/Camera.i: src/Gameplay/Camera.cpp.i

.PHONY : src/Gameplay/Camera.i

# target to preprocess a source file
src/Gameplay/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Gameplay/Camera.cpp.i
.PHONY : src/Gameplay/Camera.cpp.i

src/Gameplay/Camera.s: src/Gameplay/Camera.cpp.s

.PHONY : src/Gameplay/Camera.s

# target to generate assembly for a file
src/Gameplay/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Gameplay/Camera.cpp.s
.PHONY : src/Gameplay/Camera.cpp.s

src/Gameplay/Level.o: src/Gameplay/Level.cpp.o

.PHONY : src/Gameplay/Level.o

# target to build an object file
src/Gameplay/Level.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Gameplay/Level.cpp.o
.PHONY : src/Gameplay/Level.cpp.o

src/Gameplay/Level.i: src/Gameplay/Level.cpp.i

.PHONY : src/Gameplay/Level.i

# target to preprocess a source file
src/Gameplay/Level.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Gameplay/Level.cpp.i
.PHONY : src/Gameplay/Level.cpp.i

src/Gameplay/Level.s: src/Gameplay/Level.cpp.s

.PHONY : src/Gameplay/Level.s

# target to generate assembly for a file
src/Gameplay/Level.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Gameplay/Level.cpp.s
.PHONY : src/Gameplay/Level.cpp.s

src/Input/Input.o: src/Input/Input.cpp.o

.PHONY : src/Input/Input.o

# target to build an object file
src/Input/Input.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Input/Input.cpp.o
.PHONY : src/Input/Input.cpp.o

src/Input/Input.i: src/Input/Input.cpp.i

.PHONY : src/Input/Input.i

# target to preprocess a source file
src/Input/Input.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Input/Input.cpp.i
.PHONY : src/Input/Input.cpp.i

src/Input/Input.s: src/Input/Input.cpp.s

.PHONY : src/Input/Input.s

# target to generate assembly for a file
src/Input/Input.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Input/Input.cpp.s
.PHONY : src/Input/Input.cpp.s

src/Physics/CharacterController.o: src/Physics/CharacterController.cpp.o

.PHONY : src/Physics/CharacterController.o

# target to build an object file
src/Physics/CharacterController.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/CharacterController.cpp.o
.PHONY : src/Physics/CharacterController.cpp.o

src/Physics/CharacterController.i: src/Physics/CharacterController.cpp.i

.PHONY : src/Physics/CharacterController.i

# target to preprocess a source file
src/Physics/CharacterController.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/CharacterController.cpp.i
.PHONY : src/Physics/CharacterController.cpp.i

src/Physics/CharacterController.s: src/Physics/CharacterController.cpp.s

.PHONY : src/Physics/CharacterController.s

# target to generate assembly for a file
src/Physics/CharacterController.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/CharacterController.cpp.s
.PHONY : src/Physics/CharacterController.cpp.s

src/Physics/Cloth.o: src/Physics/Cloth.cpp.o

.PHONY : src/Physics/Cloth.o

# target to build an object file
src/Physics/Cloth.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/Cloth.cpp.o
.PHONY : src/Physics/Cloth.cpp.o

src/Physics/Cloth.i: src/Physics/Cloth.cpp.i

.PHONY : src/Physics/Cloth.i

# target to preprocess a source file
src/Physics/Cloth.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/Cloth.cpp.i
.PHONY : src/Physics/Cloth.cpp.i

src/Physics/Cloth.s: src/Physics/Cloth.cpp.s

.PHONY : src/Physics/Cloth.s

# target to generate assembly for a file
src/Physics/Cloth.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/Cloth.cpp.s
.PHONY : src/Physics/Cloth.cpp.s

src/Physics/ErrorCallback.o: src/Physics/ErrorCallback.cpp.o

.PHONY : src/Physics/ErrorCallback.o

# target to build an object file
src/Physics/ErrorCallback.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/ErrorCallback.cpp.o
.PHONY : src/Physics/ErrorCallback.cpp.o

src/Physics/ErrorCallback.i: src/Physics/ErrorCallback.cpp.i

.PHONY : src/Physics/ErrorCallback.i

# target to preprocess a source file
src/Physics/ErrorCallback.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/ErrorCallback.cpp.i
.PHONY : src/Physics/ErrorCallback.cpp.i

src/Physics/ErrorCallback.s: src/Physics/ErrorCallback.cpp.s

.PHONY : src/Physics/ErrorCallback.s

# target to generate assembly for a file
src/Physics/ErrorCallback.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/ErrorCallback.cpp.s
.PHONY : src/Physics/ErrorCallback.cpp.s

src/Physics/PhysicsSystem.o: src/Physics/PhysicsSystem.cpp.o

.PHONY : src/Physics/PhysicsSystem.o

# target to build an object file
src/Physics/PhysicsSystem.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/PhysicsSystem.cpp.o
.PHONY : src/Physics/PhysicsSystem.cpp.o

src/Physics/PhysicsSystem.i: src/Physics/PhysicsSystem.cpp.i

.PHONY : src/Physics/PhysicsSystem.i

# target to preprocess a source file
src/Physics/PhysicsSystem.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/PhysicsSystem.cpp.i
.PHONY : src/Physics/PhysicsSystem.cpp.i

src/Physics/PhysicsSystem.s: src/Physics/PhysicsSystem.cpp.s

.PHONY : src/Physics/PhysicsSystem.s

# target to generate assembly for a file
src/Physics/PhysicsSystem.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/PhysicsSystem.cpp.s
.PHONY : src/Physics/PhysicsSystem.cpp.s

src/Physics/RigidBody.o: src/Physics/RigidBody.cpp.o

.PHONY : src/Physics/RigidBody.o

# target to build an object file
src/Physics/RigidBody.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/RigidBody.cpp.o
.PHONY : src/Physics/RigidBody.cpp.o

src/Physics/RigidBody.i: src/Physics/RigidBody.cpp.i

.PHONY : src/Physics/RigidBody.i

# target to preprocess a source file
src/Physics/RigidBody.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/RigidBody.cpp.i
.PHONY : src/Physics/RigidBody.cpp.i

src/Physics/RigidBody.s: src/Physics/RigidBody.cpp.s

.PHONY : src/Physics/RigidBody.s

# target to generate assembly for a file
src/Physics/RigidBody.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/RigidBody.cpp.s
.PHONY : src/Physics/RigidBody.cpp.s

src/Physics/StaticBody.o: src/Physics/StaticBody.cpp.o

.PHONY : src/Physics/StaticBody.o

# target to build an object file
src/Physics/StaticBody.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/StaticBody.cpp.o
.PHONY : src/Physics/StaticBody.cpp.o

src/Physics/StaticBody.i: src/Physics/StaticBody.cpp.i

.PHONY : src/Physics/StaticBody.i

# target to preprocess a source file
src/Physics/StaticBody.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/StaticBody.cpp.i
.PHONY : src/Physics/StaticBody.cpp.i

src/Physics/StaticBody.s: src/Physics/StaticBody.cpp.s

.PHONY : src/Physics/StaticBody.s

# target to generate assembly for a file
src/Physics/StaticBody.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Physics/StaticBody.cpp.s
.PHONY : src/Physics/StaticBody.cpp.s

src/Render/ArrayBuffer.o: src/Render/ArrayBuffer.cpp.o

.PHONY : src/Render/ArrayBuffer.o

# target to build an object file
src/Render/ArrayBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/ArrayBuffer.cpp.o
.PHONY : src/Render/ArrayBuffer.cpp.o

src/Render/ArrayBuffer.i: src/Render/ArrayBuffer.cpp.i

.PHONY : src/Render/ArrayBuffer.i

# target to preprocess a source file
src/Render/ArrayBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/ArrayBuffer.cpp.i
.PHONY : src/Render/ArrayBuffer.cpp.i

src/Render/ArrayBuffer.s: src/Render/ArrayBuffer.cpp.s

.PHONY : src/Render/ArrayBuffer.s

# target to generate assembly for a file
src/Render/ArrayBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/ArrayBuffer.cpp.s
.PHONY : src/Render/ArrayBuffer.cpp.s

src/Render/BasePass.o: src/Render/BasePass.cpp.o

.PHONY : src/Render/BasePass.o

# target to build an object file
src/Render/BasePass.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/BasePass.cpp.o
.PHONY : src/Render/BasePass.cpp.o

src/Render/BasePass.i: src/Render/BasePass.cpp.i

.PHONY : src/Render/BasePass.i

# target to preprocess a source file
src/Render/BasePass.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/BasePass.cpp.i
.PHONY : src/Render/BasePass.cpp.i

src/Render/BasePass.s: src/Render/BasePass.cpp.s

.PHONY : src/Render/BasePass.s

# target to generate assembly for a file
src/Render/BasePass.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/BasePass.cpp.s
.PHONY : src/Render/BasePass.cpp.s

src/Render/Cubemap.o: src/Render/Cubemap.cpp.o

.PHONY : src/Render/Cubemap.o

# target to build an object file
src/Render/Cubemap.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Cubemap.cpp.o
.PHONY : src/Render/Cubemap.cpp.o

src/Render/Cubemap.i: src/Render/Cubemap.cpp.i

.PHONY : src/Render/Cubemap.i

# target to preprocess a source file
src/Render/Cubemap.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Cubemap.cpp.i
.PHONY : src/Render/Cubemap.cpp.i

src/Render/Cubemap.s: src/Render/Cubemap.cpp.s

.PHONY : src/Render/Cubemap.s

# target to generate assembly for a file
src/Render/Cubemap.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Cubemap.cpp.s
.PHONY : src/Render/Cubemap.cpp.s

src/Render/Framebuffer.o: src/Render/Framebuffer.cpp.o

.PHONY : src/Render/Framebuffer.o

# target to build an object file
src/Render/Framebuffer.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Framebuffer.cpp.o
.PHONY : src/Render/Framebuffer.cpp.o

src/Render/Framebuffer.i: src/Render/Framebuffer.cpp.i

.PHONY : src/Render/Framebuffer.i

# target to preprocess a source file
src/Render/Framebuffer.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Framebuffer.cpp.i
.PHONY : src/Render/Framebuffer.cpp.i

src/Render/Framebuffer.s: src/Render/Framebuffer.cpp.s

.PHONY : src/Render/Framebuffer.s

# target to generate assembly for a file
src/Render/Framebuffer.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Framebuffer.cpp.s
.PHONY : src/Render/Framebuffer.cpp.s

src/Render/Geometry/ScreenQuad.o: src/Render/Geometry/ScreenQuad.cpp.o

.PHONY : src/Render/Geometry/ScreenQuad.o

# target to build an object file
src/Render/Geometry/ScreenQuad.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Geometry/ScreenQuad.cpp.o
.PHONY : src/Render/Geometry/ScreenQuad.cpp.o

src/Render/Geometry/ScreenQuad.i: src/Render/Geometry/ScreenQuad.cpp.i

.PHONY : src/Render/Geometry/ScreenQuad.i

# target to preprocess a source file
src/Render/Geometry/ScreenQuad.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Geometry/ScreenQuad.cpp.i
.PHONY : src/Render/Geometry/ScreenQuad.cpp.i

src/Render/Geometry/ScreenQuad.s: src/Render/Geometry/ScreenQuad.cpp.s

.PHONY : src/Render/Geometry/ScreenQuad.s

# target to generate assembly for a file
src/Render/Geometry/ScreenQuad.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Geometry/ScreenQuad.cpp.s
.PHONY : src/Render/Geometry/ScreenQuad.cpp.s

src/Render/Geometry/SkinnedMeshLoader.o: src/Render/Geometry/SkinnedMeshLoader.cpp.o

.PHONY : src/Render/Geometry/SkinnedMeshLoader.o

# target to build an object file
src/Render/Geometry/SkinnedMeshLoader.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Geometry/SkinnedMeshLoader.cpp.o
.PHONY : src/Render/Geometry/SkinnedMeshLoader.cpp.o

src/Render/Geometry/SkinnedMeshLoader.i: src/Render/Geometry/SkinnedMeshLoader.cpp.i

.PHONY : src/Render/Geometry/SkinnedMeshLoader.i

# target to preprocess a source file
src/Render/Geometry/SkinnedMeshLoader.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Geometry/SkinnedMeshLoader.cpp.i
.PHONY : src/Render/Geometry/SkinnedMeshLoader.cpp.i

src/Render/Geometry/SkinnedMeshLoader.s: src/Render/Geometry/SkinnedMeshLoader.cpp.s

.PHONY : src/Render/Geometry/SkinnedMeshLoader.s

# target to generate assembly for a file
src/Render/Geometry/SkinnedMeshLoader.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Geometry/SkinnedMeshLoader.cpp.s
.PHONY : src/Render/Geometry/SkinnedMeshLoader.cpp.s

src/Render/Geometry/StaticMeshLoader.o: src/Render/Geometry/StaticMeshLoader.cpp.o

.PHONY : src/Render/Geometry/StaticMeshLoader.o

# target to build an object file
src/Render/Geometry/StaticMeshLoader.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Geometry/StaticMeshLoader.cpp.o
.PHONY : src/Render/Geometry/StaticMeshLoader.cpp.o

src/Render/Geometry/StaticMeshLoader.i: src/Render/Geometry/StaticMeshLoader.cpp.i

.PHONY : src/Render/Geometry/StaticMeshLoader.i

# target to preprocess a source file
src/Render/Geometry/StaticMeshLoader.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Geometry/StaticMeshLoader.cpp.i
.PHONY : src/Render/Geometry/StaticMeshLoader.cpp.i

src/Render/Geometry/StaticMeshLoader.s: src/Render/Geometry/StaticMeshLoader.cpp.s

.PHONY : src/Render/Geometry/StaticMeshLoader.s

# target to generate assembly for a file
src/Render/Geometry/StaticMeshLoader.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Geometry/StaticMeshLoader.cpp.s
.PHONY : src/Render/Geometry/StaticMeshLoader.cpp.s

src/Render/Image.o: src/Render/Image.cpp.o

.PHONY : src/Render/Image.o

# target to build an object file
src/Render/Image.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Image.cpp.o
.PHONY : src/Render/Image.cpp.o

src/Render/Image.i: src/Render/Image.cpp.i

.PHONY : src/Render/Image.i

# target to preprocess a source file
src/Render/Image.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Image.cpp.i
.PHONY : src/Render/Image.cpp.i

src/Render/Image.s: src/Render/Image.cpp.s

.PHONY : src/Render/Image.s

# target to generate assembly for a file
src/Render/Image.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Image.cpp.s
.PHONY : src/Render/Image.cpp.s

src/Render/LineRenderer.o: src/Render/LineRenderer.cpp.o

.PHONY : src/Render/LineRenderer.o

# target to build an object file
src/Render/LineRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/LineRenderer.cpp.o
.PHONY : src/Render/LineRenderer.cpp.o

src/Render/LineRenderer.i: src/Render/LineRenderer.cpp.i

.PHONY : src/Render/LineRenderer.i

# target to preprocess a source file
src/Render/LineRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/LineRenderer.cpp.i
.PHONY : src/Render/LineRenderer.cpp.i

src/Render/LineRenderer.s: src/Render/LineRenderer.cpp.s

.PHONY : src/Render/LineRenderer.s

# target to generate assembly for a file
src/Render/LineRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/LineRenderer.cpp.s
.PHONY : src/Render/LineRenderer.cpp.s

src/Render/Material.o: src/Render/Material.cpp.o

.PHONY : src/Render/Material.o

# target to build an object file
src/Render/Material.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Material.cpp.o
.PHONY : src/Render/Material.cpp.o

src/Render/Material.i: src/Render/Material.cpp.i

.PHONY : src/Render/Material.i

# target to preprocess a source file
src/Render/Material.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Material.cpp.i
.PHONY : src/Render/Material.cpp.i

src/Render/Material.s: src/Render/Material.cpp.s

.PHONY : src/Render/Material.s

# target to generate assembly for a file
src/Render/Material.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Material.cpp.s
.PHONY : src/Render/Material.cpp.s

src/Render/OpenGL.o: src/Render/OpenGL.cpp.o

.PHONY : src/Render/OpenGL.o

# target to build an object file
src/Render/OpenGL.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/OpenGL.cpp.o
.PHONY : src/Render/OpenGL.cpp.o

src/Render/OpenGL.i: src/Render/OpenGL.cpp.i

.PHONY : src/Render/OpenGL.i

# target to preprocess a source file
src/Render/OpenGL.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/OpenGL.cpp.i
.PHONY : src/Render/OpenGL.cpp.i

src/Render/OpenGL.s: src/Render/OpenGL.cpp.s

.PHONY : src/Render/OpenGL.s

# target to generate assembly for a file
src/Render/OpenGL.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/OpenGL.cpp.s
.PHONY : src/Render/OpenGL.cpp.s

src/Render/RenderPass.o: src/Render/RenderPass.cpp.o

.PHONY : src/Render/RenderPass.o

# target to build an object file
src/Render/RenderPass.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/RenderPass.cpp.o
.PHONY : src/Render/RenderPass.cpp.o

src/Render/RenderPass.i: src/Render/RenderPass.cpp.i

.PHONY : src/Render/RenderPass.i

# target to preprocess a source file
src/Render/RenderPass.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/RenderPass.cpp.i
.PHONY : src/Render/RenderPass.cpp.i

src/Render/RenderPass.s: src/Render/RenderPass.cpp.s

.PHONY : src/Render/RenderPass.s

# target to generate assembly for a file
src/Render/RenderPass.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/RenderPass.cpp.s
.PHONY : src/Render/RenderPass.cpp.s

src/Render/Scene/RenderCloth.o: src/Render/Scene/RenderCloth.cpp.o

.PHONY : src/Render/Scene/RenderCloth.o

# target to build an object file
src/Render/Scene/RenderCloth.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderCloth.cpp.o
.PHONY : src/Render/Scene/RenderCloth.cpp.o

src/Render/Scene/RenderCloth.i: src/Render/Scene/RenderCloth.cpp.i

.PHONY : src/Render/Scene/RenderCloth.i

# target to preprocess a source file
src/Render/Scene/RenderCloth.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderCloth.cpp.i
.PHONY : src/Render/Scene/RenderCloth.cpp.i

src/Render/Scene/RenderCloth.s: src/Render/Scene/RenderCloth.cpp.s

.PHONY : src/Render/Scene/RenderCloth.s

# target to generate assembly for a file
src/Render/Scene/RenderCloth.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderCloth.cpp.s
.PHONY : src/Render/Scene/RenderCloth.cpp.s

src/Render/Scene/RenderEntity.o: src/Render/Scene/RenderEntity.cpp.o

.PHONY : src/Render/Scene/RenderEntity.o

# target to build an object file
src/Render/Scene/RenderEntity.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderEntity.cpp.o
.PHONY : src/Render/Scene/RenderEntity.cpp.o

src/Render/Scene/RenderEntity.i: src/Render/Scene/RenderEntity.cpp.i

.PHONY : src/Render/Scene/RenderEntity.i

# target to preprocess a source file
src/Render/Scene/RenderEntity.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderEntity.cpp.i
.PHONY : src/Render/Scene/RenderEntity.cpp.i

src/Render/Scene/RenderEntity.s: src/Render/Scene/RenderEntity.cpp.s

.PHONY : src/Render/Scene/RenderEntity.s

# target to generate assembly for a file
src/Render/Scene/RenderEntity.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderEntity.cpp.s
.PHONY : src/Render/Scene/RenderEntity.cpp.s

src/Render/Scene/RenderFlare.o: src/Render/Scene/RenderFlare.cpp.o

.PHONY : src/Render/Scene/RenderFlare.o

# target to build an object file
src/Render/Scene/RenderFlare.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderFlare.cpp.o
.PHONY : src/Render/Scene/RenderFlare.cpp.o

src/Render/Scene/RenderFlare.i: src/Render/Scene/RenderFlare.cpp.i

.PHONY : src/Render/Scene/RenderFlare.i

# target to preprocess a source file
src/Render/Scene/RenderFlare.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderFlare.cpp.i
.PHONY : src/Render/Scene/RenderFlare.cpp.i

src/Render/Scene/RenderFlare.s: src/Render/Scene/RenderFlare.cpp.s

.PHONY : src/Render/Scene/RenderFlare.s

# target to generate assembly for a file
src/Render/Scene/RenderFlare.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderFlare.cpp.s
.PHONY : src/Render/Scene/RenderFlare.cpp.s

src/Render/Scene/RenderLight.o: src/Render/Scene/RenderLight.cpp.o

.PHONY : src/Render/Scene/RenderLight.o

# target to build an object file
src/Render/Scene/RenderLight.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderLight.cpp.o
.PHONY : src/Render/Scene/RenderLight.cpp.o

src/Render/Scene/RenderLight.i: src/Render/Scene/RenderLight.cpp.i

.PHONY : src/Render/Scene/RenderLight.i

# target to preprocess a source file
src/Render/Scene/RenderLight.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderLight.cpp.i
.PHONY : src/Render/Scene/RenderLight.cpp.i

src/Render/Scene/RenderLight.s: src/Render/Scene/RenderLight.cpp.s

.PHONY : src/Render/Scene/RenderLight.s

# target to generate assembly for a file
src/Render/Scene/RenderLight.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderLight.cpp.s
.PHONY : src/Render/Scene/RenderLight.cpp.s

src/Render/Scene/RenderMesh.o: src/Render/Scene/RenderMesh.cpp.o

.PHONY : src/Render/Scene/RenderMesh.o

# target to build an object file
src/Render/Scene/RenderMesh.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderMesh.cpp.o
.PHONY : src/Render/Scene/RenderMesh.cpp.o

src/Render/Scene/RenderMesh.i: src/Render/Scene/RenderMesh.cpp.i

.PHONY : src/Render/Scene/RenderMesh.i

# target to preprocess a source file
src/Render/Scene/RenderMesh.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderMesh.cpp.i
.PHONY : src/Render/Scene/RenderMesh.cpp.i

src/Render/Scene/RenderMesh.s: src/Render/Scene/RenderMesh.cpp.s

.PHONY : src/Render/Scene/RenderMesh.s

# target to generate assembly for a file
src/Render/Scene/RenderMesh.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderMesh.cpp.s
.PHONY : src/Render/Scene/RenderMesh.cpp.s

src/Render/Scene/RenderScene.o: src/Render/Scene/RenderScene.cpp.o

.PHONY : src/Render/Scene/RenderScene.o

# target to build an object file
src/Render/Scene/RenderScene.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderScene.cpp.o
.PHONY : src/Render/Scene/RenderScene.cpp.o

src/Render/Scene/RenderScene.i: src/Render/Scene/RenderScene.cpp.i

.PHONY : src/Render/Scene/RenderScene.i

# target to preprocess a source file
src/Render/Scene/RenderScene.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderScene.cpp.i
.PHONY : src/Render/Scene/RenderScene.cpp.i

src/Render/Scene/RenderScene.s: src/Render/Scene/RenderScene.cpp.s

.PHONY : src/Render/Scene/RenderScene.s

# target to generate assembly for a file
src/Render/Scene/RenderScene.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderScene.cpp.s
.PHONY : src/Render/Scene/RenderScene.cpp.s

src/Render/Scene/RenderSkinnedMesh.o: src/Render/Scene/RenderSkinnedMesh.cpp.o

.PHONY : src/Render/Scene/RenderSkinnedMesh.o

# target to build an object file
src/Render/Scene/RenderSkinnedMesh.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderSkinnedMesh.cpp.o
.PHONY : src/Render/Scene/RenderSkinnedMesh.cpp.o

src/Render/Scene/RenderSkinnedMesh.i: src/Render/Scene/RenderSkinnedMesh.cpp.i

.PHONY : src/Render/Scene/RenderSkinnedMesh.i

# target to preprocess a source file
src/Render/Scene/RenderSkinnedMesh.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderSkinnedMesh.cpp.i
.PHONY : src/Render/Scene/RenderSkinnedMesh.cpp.i

src/Render/Scene/RenderSkinnedMesh.s: src/Render/Scene/RenderSkinnedMesh.cpp.s

.PHONY : src/Render/Scene/RenderSkinnedMesh.s

# target to generate assembly for a file
src/Render/Scene/RenderSkinnedMesh.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Scene/RenderSkinnedMesh.cpp.s
.PHONY : src/Render/Scene/RenderSkinnedMesh.cpp.s

src/Render/SceneRenderer.o: src/Render/SceneRenderer.cpp.o

.PHONY : src/Render/SceneRenderer.o

# target to build an object file
src/Render/SceneRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/SceneRenderer.cpp.o
.PHONY : src/Render/SceneRenderer.cpp.o

src/Render/SceneRenderer.i: src/Render/SceneRenderer.cpp.i

.PHONY : src/Render/SceneRenderer.i

# target to preprocess a source file
src/Render/SceneRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/SceneRenderer.cpp.i
.PHONY : src/Render/SceneRenderer.cpp.i

src/Render/SceneRenderer.s: src/Render/SceneRenderer.cpp.s

.PHONY : src/Render/SceneRenderer.s

# target to generate assembly for a file
src/Render/SceneRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/SceneRenderer.cpp.s
.PHONY : src/Render/SceneRenderer.cpp.s

src/Render/Shader.o: src/Render/Shader.cpp.o

.PHONY : src/Render/Shader.o

# target to build an object file
src/Render/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Shader.cpp.o
.PHONY : src/Render/Shader.cpp.o

src/Render/Shader.i: src/Render/Shader.cpp.i

.PHONY : src/Render/Shader.i

# target to preprocess a source file
src/Render/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Shader.cpp.i
.PHONY : src/Render/Shader.cpp.i

src/Render/Shader.s: src/Render/Shader.cpp.s

.PHONY : src/Render/Shader.s

# target to generate assembly for a file
src/Render/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Shader.cpp.s
.PHONY : src/Render/Shader.cpp.s

src/Render/ShadowPass.o: src/Render/ShadowPass.cpp.o

.PHONY : src/Render/ShadowPass.o

# target to build an object file
src/Render/ShadowPass.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/ShadowPass.cpp.o
.PHONY : src/Render/ShadowPass.cpp.o

src/Render/ShadowPass.i: src/Render/ShadowPass.cpp.i

.PHONY : src/Render/ShadowPass.i

# target to preprocess a source file
src/Render/ShadowPass.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/ShadowPass.cpp.i
.PHONY : src/Render/ShadowPass.cpp.i

src/Render/ShadowPass.s: src/Render/ShadowPass.cpp.s

.PHONY : src/Render/ShadowPass.s

# target to generate assembly for a file
src/Render/ShadowPass.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/ShadowPass.cpp.s
.PHONY : src/Render/ShadowPass.cpp.s

src/Render/Texture.o: src/Render/Texture.cpp.o

.PHONY : src/Render/Texture.o

# target to build an object file
src/Render/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Texture.cpp.o
.PHONY : src/Render/Texture.cpp.o

src/Render/Texture.i: src/Render/Texture.cpp.i

.PHONY : src/Render/Texture.i

# target to preprocess a source file
src/Render/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Texture.cpp.i
.PHONY : src/Render/Texture.cpp.i

src/Render/Texture.s: src/Render/Texture.cpp.s

.PHONY : src/Render/Texture.s

# target to generate assembly for a file
src/Render/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/Texture.cpp.s
.PHONY : src/Render/Texture.cpp.s

src/Render/VertexArray.o: src/Render/VertexArray.cpp.o

.PHONY : src/Render/VertexArray.o

# target to build an object file
src/Render/VertexArray.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/VertexArray.cpp.o
.PHONY : src/Render/VertexArray.cpp.o

src/Render/VertexArray.i: src/Render/VertexArray.cpp.i

.PHONY : src/Render/VertexArray.i

# target to preprocess a source file
src/Render/VertexArray.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/VertexArray.cpp.i
.PHONY : src/Render/VertexArray.cpp.i

src/Render/VertexArray.s: src/Render/VertexArray.cpp.s

.PHONY : src/Render/VertexArray.s

# target to generate assembly for a file
src/Render/VertexArray.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Render/VertexArray.cpp.s
.PHONY : src/Render/VertexArray.cpp.s

src/Resource/AnimationCache.o: src/Resource/AnimationCache.cpp.o

.PHONY : src/Resource/AnimationCache.o

# target to build an object file
src/Resource/AnimationCache.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/AnimationCache.cpp.o
.PHONY : src/Resource/AnimationCache.cpp.o

src/Resource/AnimationCache.i: src/Resource/AnimationCache.cpp.i

.PHONY : src/Resource/AnimationCache.i

# target to preprocess a source file
src/Resource/AnimationCache.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/AnimationCache.cpp.i
.PHONY : src/Resource/AnimationCache.cpp.i

src/Resource/AnimationCache.s: src/Resource/AnimationCache.cpp.s

.PHONY : src/Resource/AnimationCache.s

# target to generate assembly for a file
src/Resource/AnimationCache.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/AnimationCache.cpp.s
.PHONY : src/Resource/AnimationCache.cpp.s

src/Resource/MaterialCache.o: src/Resource/MaterialCache.cpp.o

.PHONY : src/Resource/MaterialCache.o

# target to build an object file
src/Resource/MaterialCache.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/MaterialCache.cpp.o
.PHONY : src/Resource/MaterialCache.cpp.o

src/Resource/MaterialCache.i: src/Resource/MaterialCache.cpp.i

.PHONY : src/Resource/MaterialCache.i

# target to preprocess a source file
src/Resource/MaterialCache.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/MaterialCache.cpp.i
.PHONY : src/Resource/MaterialCache.cpp.i

src/Resource/MaterialCache.s: src/Resource/MaterialCache.cpp.s

.PHONY : src/Resource/MaterialCache.s

# target to generate assembly for a file
src/Resource/MaterialCache.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/MaterialCache.cpp.s
.PHONY : src/Resource/MaterialCache.cpp.s

src/Resource/MeshCache.o: src/Resource/MeshCache.cpp.o

.PHONY : src/Resource/MeshCache.o

# target to build an object file
src/Resource/MeshCache.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/MeshCache.cpp.o
.PHONY : src/Resource/MeshCache.cpp.o

src/Resource/MeshCache.i: src/Resource/MeshCache.cpp.i

.PHONY : src/Resource/MeshCache.i

# target to preprocess a source file
src/Resource/MeshCache.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/MeshCache.cpp.i
.PHONY : src/Resource/MeshCache.cpp.i

src/Resource/MeshCache.s: src/Resource/MeshCache.cpp.s

.PHONY : src/Resource/MeshCache.s

# target to generate assembly for a file
src/Resource/MeshCache.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/MeshCache.cpp.s
.PHONY : src/Resource/MeshCache.cpp.s

src/Resource/TextureCache.o: src/Resource/TextureCache.cpp.o

.PHONY : src/Resource/TextureCache.o

# target to build an object file
src/Resource/TextureCache.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/TextureCache.cpp.o
.PHONY : src/Resource/TextureCache.cpp.o

src/Resource/TextureCache.i: src/Resource/TextureCache.cpp.i

.PHONY : src/Resource/TextureCache.i

# target to preprocess a source file
src/Resource/TextureCache.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/TextureCache.cpp.i
.PHONY : src/Resource/TextureCache.cpp.i

src/Resource/TextureCache.s: src/Resource/TextureCache.cpp.s

.PHONY : src/Resource/TextureCache.s

# target to generate assembly for a file
src/Resource/TextureCache.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/Resource/TextureCache.cpp.s
.PHONY : src/Resource/TextureCache.cpp.s

src/ThirdParty/ImGui/imgui.o: src/ThirdParty/ImGui/imgui.cpp.o

.PHONY : src/ThirdParty/ImGui/imgui.o

# target to build an object file
src/ThirdParty/ImGui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui.cpp.o
.PHONY : src/ThirdParty/ImGui/imgui.cpp.o

src/ThirdParty/ImGui/imgui.i: src/ThirdParty/ImGui/imgui.cpp.i

.PHONY : src/ThirdParty/ImGui/imgui.i

# target to preprocess a source file
src/ThirdParty/ImGui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui.cpp.i
.PHONY : src/ThirdParty/ImGui/imgui.cpp.i

src/ThirdParty/ImGui/imgui.s: src/ThirdParty/ImGui/imgui.cpp.s

.PHONY : src/ThirdParty/ImGui/imgui.s

# target to generate assembly for a file
src/ThirdParty/ImGui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui.cpp.s
.PHONY : src/ThirdParty/ImGui/imgui.cpp.s

src/ThirdParty/ImGui/imgui_demo.o: src/ThirdParty/ImGui/imgui_demo.cpp.o

.PHONY : src/ThirdParty/ImGui/imgui_demo.o

# target to build an object file
src/ThirdParty/ImGui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_demo.cpp.o
.PHONY : src/ThirdParty/ImGui/imgui_demo.cpp.o

src/ThirdParty/ImGui/imgui_demo.i: src/ThirdParty/ImGui/imgui_demo.cpp.i

.PHONY : src/ThirdParty/ImGui/imgui_demo.i

# target to preprocess a source file
src/ThirdParty/ImGui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_demo.cpp.i
.PHONY : src/ThirdParty/ImGui/imgui_demo.cpp.i

src/ThirdParty/ImGui/imgui_demo.s: src/ThirdParty/ImGui/imgui_demo.cpp.s

.PHONY : src/ThirdParty/ImGui/imgui_demo.s

# target to generate assembly for a file
src/ThirdParty/ImGui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_demo.cpp.s
.PHONY : src/ThirdParty/ImGui/imgui_demo.cpp.s

src/ThirdParty/ImGui/imgui_draw.o: src/ThirdParty/ImGui/imgui_draw.cpp.o

.PHONY : src/ThirdParty/ImGui/imgui_draw.o

# target to build an object file
src/ThirdParty/ImGui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_draw.cpp.o
.PHONY : src/ThirdParty/ImGui/imgui_draw.cpp.o

src/ThirdParty/ImGui/imgui_draw.i: src/ThirdParty/ImGui/imgui_draw.cpp.i

.PHONY : src/ThirdParty/ImGui/imgui_draw.i

# target to preprocess a source file
src/ThirdParty/ImGui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_draw.cpp.i
.PHONY : src/ThirdParty/ImGui/imgui_draw.cpp.i

src/ThirdParty/ImGui/imgui_draw.s: src/ThirdParty/ImGui/imgui_draw.cpp.s

.PHONY : src/ThirdParty/ImGui/imgui_draw.s

# target to generate assembly for a file
src/ThirdParty/ImGui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_draw.cpp.s
.PHONY : src/ThirdParty/ImGui/imgui_draw.cpp.s

src/ThirdParty/ImGui/imgui_impl_opengl3.o: src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.o

.PHONY : src/ThirdParty/ImGui/imgui_impl_opengl3.o

# target to build an object file
src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.o
.PHONY : src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.o

src/ThirdParty/ImGui/imgui_impl_opengl3.i: src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.i

.PHONY : src/ThirdParty/ImGui/imgui_impl_opengl3.i

# target to preprocess a source file
src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.i
.PHONY : src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.i

src/ThirdParty/ImGui/imgui_impl_opengl3.s: src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.s

.PHONY : src/ThirdParty/ImGui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.s
.PHONY : src/ThirdParty/ImGui/imgui_impl_opengl3.cpp.s

src/ThirdParty/ImGui/imgui_impl_sdl.o: src/ThirdParty/ImGui/imgui_impl_sdl.cpp.o

.PHONY : src/ThirdParty/ImGui/imgui_impl_sdl.o

# target to build an object file
src/ThirdParty/ImGui/imgui_impl_sdl.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_impl_sdl.cpp.o
.PHONY : src/ThirdParty/ImGui/imgui_impl_sdl.cpp.o

src/ThirdParty/ImGui/imgui_impl_sdl.i: src/ThirdParty/ImGui/imgui_impl_sdl.cpp.i

.PHONY : src/ThirdParty/ImGui/imgui_impl_sdl.i

# target to preprocess a source file
src/ThirdParty/ImGui/imgui_impl_sdl.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_impl_sdl.cpp.i
.PHONY : src/ThirdParty/ImGui/imgui_impl_sdl.cpp.i

src/ThirdParty/ImGui/imgui_impl_sdl.s: src/ThirdParty/ImGui/imgui_impl_sdl.cpp.s

.PHONY : src/ThirdParty/ImGui/imgui_impl_sdl.s

# target to generate assembly for a file
src/ThirdParty/ImGui/imgui_impl_sdl.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_impl_sdl.cpp.s
.PHONY : src/ThirdParty/ImGui/imgui_impl_sdl.cpp.s

src/ThirdParty/ImGui/imgui_widgets.o: src/ThirdParty/ImGui/imgui_widgets.cpp.o

.PHONY : src/ThirdParty/ImGui/imgui_widgets.o

# target to build an object file
src/ThirdParty/ImGui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_widgets.cpp.o
.PHONY : src/ThirdParty/ImGui/imgui_widgets.cpp.o

src/ThirdParty/ImGui/imgui_widgets.i: src/ThirdParty/ImGui/imgui_widgets.cpp.i

.PHONY : src/ThirdParty/ImGui/imgui_widgets.i

# target to preprocess a source file
src/ThirdParty/ImGui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_widgets.cpp.i
.PHONY : src/ThirdParty/ImGui/imgui_widgets.cpp.i

src/ThirdParty/ImGui/imgui_widgets.s: src/ThirdParty/ImGui/imgui_widgets.cpp.s

.PHONY : src/ThirdParty/ImGui/imgui_widgets.s

# target to generate assembly for a file
src/ThirdParty/ImGui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/ImGui/imgui_widgets.cpp.s
.PHONY : src/ThirdParty/ImGui/imgui_widgets.cpp.s

src/ThirdParty/glm/detail/dummy.o: src/ThirdParty/glm/detail/dummy.cpp.o

.PHONY : src/ThirdParty/glm/detail/dummy.o

# target to build an object file
src/ThirdParty/glm/detail/dummy.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/glm/detail/dummy.cpp.o
.PHONY : src/ThirdParty/glm/detail/dummy.cpp.o

src/ThirdParty/glm/detail/dummy.i: src/ThirdParty/glm/detail/dummy.cpp.i

.PHONY : src/ThirdParty/glm/detail/dummy.i

# target to preprocess a source file
src/ThirdParty/glm/detail/dummy.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/glm/detail/dummy.cpp.i
.PHONY : src/ThirdParty/glm/detail/dummy.cpp.i

src/ThirdParty/glm/detail/dummy.s: src/ThirdParty/glm/detail/dummy.cpp.s

.PHONY : src/ThirdParty/glm/detail/dummy.s

# target to generate assembly for a file
src/ThirdParty/glm/detail/dummy.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/glm/detail/dummy.cpp.s
.PHONY : src/ThirdParty/glm/detail/dummy.cpp.s

src/ThirdParty/glm/detail/glm.o: src/ThirdParty/glm/detail/glm.cpp.o

.PHONY : src/ThirdParty/glm/detail/glm.o

# target to build an object file
src/ThirdParty/glm/detail/glm.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/glm/detail/glm.cpp.o
.PHONY : src/ThirdParty/glm/detail/glm.cpp.o

src/ThirdParty/glm/detail/glm.i: src/ThirdParty/glm/detail/glm.cpp.i

.PHONY : src/ThirdParty/glm/detail/glm.i

# target to preprocess a source file
src/ThirdParty/glm/detail/glm.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/glm/detail/glm.cpp.i
.PHONY : src/ThirdParty/glm/detail/glm.cpp.i

src/ThirdParty/glm/detail/glm.s: src/ThirdParty/glm/detail/glm.cpp.s

.PHONY : src/ThirdParty/glm/detail/glm.s

# target to generate assembly for a file
src/ThirdParty/glm/detail/glm.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/ThirdParty/glm/detail/glm.cpp.s
.PHONY : src/ThirdParty/glm/detail/glm.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... out"
	@echo "... edit_cache"
	@echo "... src/Animation/Clip.o"
	@echo "... src/Animation/Clip.i"
	@echo "... src/Animation/Clip.s"
	@echo "... src/Animation/Pose.o"
	@echo "... src/Animation/Pose.i"
	@echo "... src/Animation/Pose.s"
	@echo "... src/Animation/Skeleton.o"
	@echo "... src/Animation/Skeleton.i"
	@echo "... src/Animation/Skeleton.s"
	@echo "... src/Animation/SkinningData.o"
	@echo "... src/Animation/SkinningData.i"
	@echo "... src/Animation/SkinningData.s"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/Core/Config.o"
	@echo "... src/Core/Config.i"
	@echo "... src/Core/Config.s"
	@echo "... src/Core/Convert.o"
	@echo "... src/Core/Convert.i"
	@echo "... src/Core/Convert.s"
	@echo "... src/Core/Math3D.o"
	@echo "... src/Core/Math3D.i"
	@echo "... src/Core/Math3D.s"
	@echo "... src/Core/Random.o"
	@echo "... src/Core/Random.i"
	@echo "... src/Core/Random.s"
	@echo "... src/Core/Timer.o"
	@echo "... src/Core/Timer.i"
	@echo "... src/Core/Timer.s"
	@echo "... src/Debug/DebugMenu.o"
	@echo "... src/Debug/DebugMenu.i"
	@echo "... src/Debug/DebugMenu.s"
	@echo "... src/Debug/Log.o"
	@echo "... src/Debug/Log.i"
	@echo "... src/Debug/Log.s"
	@echo "... src/Gameplay/Camera.o"
	@echo "... src/Gameplay/Camera.i"
	@echo "... src/Gameplay/Camera.s"
	@echo "... src/Gameplay/Level.o"
	@echo "... src/Gameplay/Level.i"
	@echo "... src/Gameplay/Level.s"
	@echo "... src/Input/Input.o"
	@echo "... src/Input/Input.i"
	@echo "... src/Input/Input.s"
	@echo "... src/Physics/CharacterController.o"
	@echo "... src/Physics/CharacterController.i"
	@echo "... src/Physics/CharacterController.s"
	@echo "... src/Physics/Cloth.o"
	@echo "... src/Physics/Cloth.i"
	@echo "... src/Physics/Cloth.s"
	@echo "... src/Physics/ErrorCallback.o"
	@echo "... src/Physics/ErrorCallback.i"
	@echo "... src/Physics/ErrorCallback.s"
	@echo "... src/Physics/PhysicsSystem.o"
	@echo "... src/Physics/PhysicsSystem.i"
	@echo "... src/Physics/PhysicsSystem.s"
	@echo "... src/Physics/RigidBody.o"
	@echo "... src/Physics/RigidBody.i"
	@echo "... src/Physics/RigidBody.s"
	@echo "... src/Physics/StaticBody.o"
	@echo "... src/Physics/StaticBody.i"
	@echo "... src/Physics/StaticBody.s"
	@echo "... src/Render/ArrayBuffer.o"
	@echo "... src/Render/ArrayBuffer.i"
	@echo "... src/Render/ArrayBuffer.s"
	@echo "... src/Render/BasePass.o"
	@echo "... src/Render/BasePass.i"
	@echo "... src/Render/BasePass.s"
	@echo "... src/Render/Cubemap.o"
	@echo "... src/Render/Cubemap.i"
	@echo "... src/Render/Cubemap.s"
	@echo "... src/Render/Framebuffer.o"
	@echo "... src/Render/Framebuffer.i"
	@echo "... src/Render/Framebuffer.s"
	@echo "... src/Render/Geometry/ScreenQuad.o"
	@echo "... src/Render/Geometry/ScreenQuad.i"
	@echo "... src/Render/Geometry/ScreenQuad.s"
	@echo "... src/Render/Geometry/SkinnedMeshLoader.o"
	@echo "... src/Render/Geometry/SkinnedMeshLoader.i"
	@echo "... src/Render/Geometry/SkinnedMeshLoader.s"
	@echo "... src/Render/Geometry/StaticMeshLoader.o"
	@echo "... src/Render/Geometry/StaticMeshLoader.i"
	@echo "... src/Render/Geometry/StaticMeshLoader.s"
	@echo "... src/Render/Image.o"
	@echo "... src/Render/Image.i"
	@echo "... src/Render/Image.s"
	@echo "... src/Render/LineRenderer.o"
	@echo "... src/Render/LineRenderer.i"
	@echo "... src/Render/LineRenderer.s"
	@echo "... src/Render/Material.o"
	@echo "... src/Render/Material.i"
	@echo "... src/Render/Material.s"
	@echo "... src/Render/OpenGL.o"
	@echo "... src/Render/OpenGL.i"
	@echo "... src/Render/OpenGL.s"
	@echo "... src/Render/RenderPass.o"
	@echo "... src/Render/RenderPass.i"
	@echo "... src/Render/RenderPass.s"
	@echo "... src/Render/Scene/RenderCloth.o"
	@echo "... src/Render/Scene/RenderCloth.i"
	@echo "... src/Render/Scene/RenderCloth.s"
	@echo "... src/Render/Scene/RenderEntity.o"
	@echo "... src/Render/Scene/RenderEntity.i"
	@echo "... src/Render/Scene/RenderEntity.s"
	@echo "... src/Render/Scene/RenderFlare.o"
	@echo "... src/Render/Scene/RenderFlare.i"
	@echo "... src/Render/Scene/RenderFlare.s"
	@echo "... src/Render/Scene/RenderLight.o"
	@echo "... src/Render/Scene/RenderLight.i"
	@echo "... src/Render/Scene/RenderLight.s"
	@echo "... src/Render/Scene/RenderMesh.o"
	@echo "... src/Render/Scene/RenderMesh.i"
	@echo "... src/Render/Scene/RenderMesh.s"
	@echo "... src/Render/Scene/RenderScene.o"
	@echo "... src/Render/Scene/RenderScene.i"
	@echo "... src/Render/Scene/RenderScene.s"
	@echo "... src/Render/Scene/RenderSkinnedMesh.o"
	@echo "... src/Render/Scene/RenderSkinnedMesh.i"
	@echo "... src/Render/Scene/RenderSkinnedMesh.s"
	@echo "... src/Render/SceneRenderer.o"
	@echo "... src/Render/SceneRenderer.i"
	@echo "... src/Render/SceneRenderer.s"
	@echo "... src/Render/Shader.o"
	@echo "... src/Render/Shader.i"
	@echo "... src/Render/Shader.s"
	@echo "... src/Render/ShadowPass.o"
	@echo "... src/Render/ShadowPass.i"
	@echo "... src/Render/ShadowPass.s"
	@echo "... src/Render/Texture.o"
	@echo "... src/Render/Texture.i"
	@echo "... src/Render/Texture.s"
	@echo "... src/Render/VertexArray.o"
	@echo "... src/Render/VertexArray.i"
	@echo "... src/Render/VertexArray.s"
	@echo "... src/Resource/AnimationCache.o"
	@echo "... src/Resource/AnimationCache.i"
	@echo "... src/Resource/AnimationCache.s"
	@echo "... src/Resource/MaterialCache.o"
	@echo "... src/Resource/MaterialCache.i"
	@echo "... src/Resource/MaterialCache.s"
	@echo "... src/Resource/MeshCache.o"
	@echo "... src/Resource/MeshCache.i"
	@echo "... src/Resource/MeshCache.s"
	@echo "... src/Resource/TextureCache.o"
	@echo "... src/Resource/TextureCache.i"
	@echo "... src/Resource/TextureCache.s"
	@echo "... src/ThirdParty/ImGui/imgui.o"
	@echo "... src/ThirdParty/ImGui/imgui.i"
	@echo "... src/ThirdParty/ImGui/imgui.s"
	@echo "... src/ThirdParty/ImGui/imgui_demo.o"
	@echo "... src/ThirdParty/ImGui/imgui_demo.i"
	@echo "... src/ThirdParty/ImGui/imgui_demo.s"
	@echo "... src/ThirdParty/ImGui/imgui_draw.o"
	@echo "... src/ThirdParty/ImGui/imgui_draw.i"
	@echo "... src/ThirdParty/ImGui/imgui_draw.s"
	@echo "... src/ThirdParty/ImGui/imgui_impl_opengl3.o"
	@echo "... src/ThirdParty/ImGui/imgui_impl_opengl3.i"
	@echo "... src/ThirdParty/ImGui/imgui_impl_opengl3.s"
	@echo "... src/ThirdParty/ImGui/imgui_impl_sdl.o"
	@echo "... src/ThirdParty/ImGui/imgui_impl_sdl.i"
	@echo "... src/ThirdParty/ImGui/imgui_impl_sdl.s"
	@echo "... src/ThirdParty/ImGui/imgui_widgets.o"
	@echo "... src/ThirdParty/ImGui/imgui_widgets.i"
	@echo "... src/ThirdParty/ImGui/imgui_widgets.s"
	@echo "... src/ThirdParty/glm/detail/dummy.o"
	@echo "... src/ThirdParty/glm/detail/dummy.i"
	@echo "... src/ThirdParty/glm/detail/dummy.s"
	@echo "... src/ThirdParty/glm/detail/glm.o"
	@echo "... src/ThirdParty/glm/detail/glm.i"
	@echo "... src/ThirdParty/glm/detail/glm.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

